### ISSUE TITLE
Split apart actuation and logic enables

### ISSUE THREAD

**Issue by thomas-gleiforst** [MissouriMRDT/BaseStation_Software#122]
These are a bunch of different ifs so that something can appear in multiple lists and be toggled together. But we may want to be toggled independently, which would be a good future feature - the UI would be probably the hardest part of this consideration.

_Originally posted by @thomas-gleiforst in https://github.com/MissouriMRDT/BaseStation_Software/pull/114#discussion_r582542426_

**Comment by for-a-greener-dawn** [comment]
Fixed by populating the state object directly from RovecommManifest. This results in the busses all being subobjects of the board that bus is a part of. Part of this fix was also accomplished by intentionally keeping names of different components, boards, and busses distinct. Specifying which boards/busses are actually toggleable has been removed as a result of programmatic population of the state object. Toggle specificity is planned to return, but is at a much lower priority as of this comment because the Rover shouldn't care if it receives a "turn on" command for a board that isn't listening for a toggle command (ie. 12v logic board).
